<?php
/**
 * Referral repository.
 *
 * @package Yazan\Rewards
 */

declare( strict_types=1 );

namespace Yazan\Rewards\Modules\Referral;

use Yazan\Rewards\Core\Database\AbstractRepository;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Reads/writes the `referrals` table — the referral attribution funnel
 * (signed_up → converted).
 */
final class ReferralRepository extends AbstractRepository {

	/**
	 * @inheritDoc
	 */
	protected function table_name(): string {
		return 'referrals';
	}

	/**
	 * The referral row where this user is the referred party, if any.
	 *
	 * @param int $referred_user_id Referred user id.
	 * @return object|null
	 */
	public function find_by_referred( int $referred_user_id ): ?object {
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE referred_user_id = %d ORDER BY id ASC LIMIT 1", $referred_user_id ) );
		return $row ?: null;
	}

	/**
	 * Create a signed-up referral row.
	 *
	 * @param array $data referrer_user_id, referred_user_id, code, ip_hash, email_hash.
	 * @return int
	 */
	public function create_signup( array $data ): int {
		return $this->insert(
			array(
				'referrer_user_id' => (int) $data['referrer_user_id'],
				'referred_user_id' => (int) $data['referred_user_id'],
				'code'             => sanitize_text_field( (string) ( $data['code'] ?? '' ) ),
				'click_token'      => sanitize_text_field( (string) ( $data['click_token'] ?? '' ) ),
				'ip_hash'          => sanitize_text_field( (string) ( $data['ip_hash'] ?? '' ) ),
				'email_hash'       => sanitize_text_field( (string) ( $data['email_hash'] ?? '' ) ),
				'status'           => 'signed_up',
				'order_id'         => 0,
				'reward_points'    => 0,
				'created_at'       => current_time( 'mysql' ),
				'converted_at'     => '0000-00-00 00:00:00',
			),
			array( '%d', '%d', '%s', '%s', '%s', '%s', '%s', '%d', '%d', '%s', '%s' )
		);
	}

	/**
	 * Mark a referral converted (first qualifying order). The per-level reward
	 * amounts are recorded in the earnings ledger and rolled up onto this row via
	 * {@see self::add_reward_points()} / {@see self::add_points_generated()} when
	 * each earning is settled, so this only flips the funnel status.
	 *
	 * @param int $id       Referral row id.
	 * @param int $order_id Order id.
	 * @return void
	 */
	public function mark_converted( int $id, int $order_id ): void {
		$this->update(
			array(
				'status'       => 'converted',
				'order_id'     => $order_id,
				'converted_at' => current_time( 'mysql' ),
			),
			array( 'id' => $id ),
			array( '%s', '%d', '%s' ),
			array( '%d' )
		);
	}

	/**
	 * Add to the direct (L1) referrer's rolled-up reward points for this referral.
	 *
	 * @param int $id     Referral row id.
	 * @param int $points Points to add.
	 * @return void
	 */
	public function add_reward_points( int $id, int $points ): void {
		if ( $points <= 0 ) {
			return;
		}
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$wpdb->query( $wpdb->prepare( "UPDATE {$table} SET reward_points = reward_points + %d WHERE id = %d", $points, $id ) );
	}

	/**
	 * Accumulate an order's value onto the referred customer's row (called for
	 * EVERY order they place, so "generated revenue" reflects lifetime value even
	 * though a reward is paid only on the first order).
	 *
	 * @param int   $referred_user_id Referred customer.
	 * @param float $order_total      Order total.
	 * @return void
	 */
	public function record_order( int $referred_user_id, float $order_total ): void {
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$wpdb->query(
			$wpdb->prepare(
				"UPDATE {$table}
				 SET revenue_total = revenue_total + %f, orders_count = orders_count + 1, last_order_at = %s
				 WHERE referred_user_id = %d",
				$order_total,
				current_time( 'mysql' ),
				$referred_user_id
			)
		);
	}

	/**
	 * Add to the points generated by a referral (across all levels + welcome bonus).
	 *
	 * @param int $id     Referral row id.
	 * @param int $points Points to add.
	 * @return void
	 */
	public function add_points_generated( int $id, int $points ): void {
		if ( $points <= 0 ) {
			return;
		}
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$wpdb->query( $wpdb->prepare( "UPDATE {$table} SET points_generated = points_generated + %d WHERE id = %d", $points, $id ) );
	}

	/**
	 * A referrer's direct downline rows (the people they invited), newest first.
	 *
	 * @param int $referrer_user_id Referrer.
	 * @param int $limit            Max rows.
	 * @return object[]
	 */
	public function for_referrer( int $referrer_user_id, int $limit = 100 ): array {
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		$limit = max( 1, min( 500, $limit ) );
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$rows = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$table} WHERE referrer_user_id = %d ORDER BY id DESC LIMIT %d", $referrer_user_id, $limit ) );
		return is_array( $rows ) ? $rows : array();
	}

	/**
	 * The referred_user_ids a referrer directly invited (for tree traversal).
	 *
	 * @param int $referrer_user_id Referrer.
	 * @return int[]
	 */
	public function referred_ids( int $referrer_user_id ): array {
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$ids = $wpdb->get_col( $wpdb->prepare( "SELECT referred_user_id FROM {$table} WHERE referrer_user_id = %d", $referrer_user_id ) );
		return array_map( 'intval', (array) $ids );
	}

	/**
	 * How many OTHER accounts THIS referrer has referred from the same IP hash — the
	 * meaningful self-referral-cluster signal. Scoped to the referrer so unrelated
	 * customers behind shared NAT/CGNAT (mobile carriers, offices, households) don't
	 * count toward each other's clusters and trip false positives.
	 *
	 * @param string $ip_hash          IP hash.
	 * @param int    $referrer_user_id The referrer whose downline we're clustering.
	 * @param int    $exclude_referred Referred user id to exclude (the current one).
	 * @return int
	 */
	public function count_by_ip_hash( string $ip_hash, int $referrer_user_id, int $exclude_referred = 0 ): int {
		if ( '' === $ip_hash ) {
			return 0;
		}
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		return (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$table} WHERE ip_hash = %s AND referrer_user_id = %d AND referred_user_id <> %d", $ip_hash, $referrer_user_id, $exclude_referred ) );
	}

	/**
	 * Total revenue generated by a referrer's direct downline (sum of their
	 * referred customers' lifetime order value).
	 *
	 * @param int $referrer_user_id Referrer.
	 * @return string Decimal string.
	 */
	public function revenue_generated( int $referrer_user_id ): string {
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		return (string) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(SUM(revenue_total),0) FROM {$table} WHERE referrer_user_id = %d", $referrer_user_id ) );
	}

	/**
	 * Store-wide referral metrics (for analytics): total revenue generated by all
	 * referred customers, plus signup/conversion counts.
	 *
	 * @return array{revenue:string,signups:int,conversions:int}
	 */
	public function global_stats(): array {
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$revenue     = (string) $wpdb->get_var( "SELECT COALESCE(SUM(revenue_total),0) FROM {$table}" );
		$signups     = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$table}" );
		$conversions = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$table} WHERE status = 'converted'" );
		// phpcs:enable
		return array( 'revenue' => $revenue, 'signups' => $signups, 'conversions' => $conversions );
	}

	/**
	 * Aggregate stats for a referrer (for their dashboard).
	 *
	 * @param int $referrer_user_id Referrer user id.
	 * @return array{signups:int,conversions:int,points_earned:int,revenue:string,points_generated:int}
	 */
	public function stats_for_referrer( int $referrer_user_id ): array {
		$wpdb  = $this->db->wpdb();
		$table = $this->table();
		$earnings = $this->db->table( 'referral_earnings' );
		// phpcs:disable WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$signups     = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$table} WHERE referrer_user_id = %d", $referrer_user_id ) );
		$conversions = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$table} WHERE referrer_user_id = %d AND status = 'converted'", $referrer_user_id ) );
		// Points EARNED by this user = their approved point earnings from the ledger
		// across every level (L1 + L2), so it agrees with the earnings-ledger total
		// shown elsewhere (the referrals.reward_points rollup is L1-only).
		$points      = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(SUM(reward_amount),0) FROM {$earnings} WHERE beneficiary_user_id = %d AND reward_kind = 'points' AND status = 'approved'", $referrer_user_id ) );
		$revenue     = (string) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(SUM(revenue_total),0) FROM {$table} WHERE referrer_user_id = %d", $referrer_user_id ) );
		$generated   = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(SUM(points_generated),0) FROM {$table} WHERE referrer_user_id = %d", $referrer_user_id ) );
		// phpcs:enable
		return array(
			'signups'          => $signups,
			'conversions'      => $conversions,
			'points_earned'    => $points,
			'revenue'          => $revenue,
			'points_generated' => $generated,
		);
	}

	/**
	 * Count of a referrer's referred customers who ever placed an attributed order
	 * (used by the ambassador stats).
	 *
	 * @param int $referrer_user_id Referrer.
	 * @return int
	 */
	public function converted_count( int $referrer_user_id ): int {
		return $this->stats_for_referrer( $referrer_user_id )['conversions'];
	}
}
